//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RenderingViews.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posudbe
    {
        public int ID { get; set; }
        public int ClanID { get; set; }
        public int KnjigaID { get; set; }
        public System.DateTime Datum { get; set; }
        public int DjelatnikID { get; set; }
        public Nullable<bool> Vraceno { get; set; }
    
        public virtual Clanovi Clanovi { get; set; }
        public virtual Djelatnici Djelatnici { get; set; }
        public virtual Knjige Knjige { get; set; }
    }
}
