//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jQueryDemo.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Predavaci
    {
        public int ID { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public Nullable<System.DateTime> DatumRodenja { get; set; }
        public string OIB { get; set; }
        public string Adresa { get; set; }
        public Nullable<int> GradID { get; set; }
        public Nullable<bool> Spol { get; set; }
        public Nullable<int> TvrtkaID { get; set; }
    
        public virtual sGradovi sGradovi { get; set; }
    }
}
