//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAnnotationDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Predavanja
    {
        public Predavanja()
        {
            this.PrijaveNaPredavanjas = new HashSet<PrijaveNaPredavanja>();
        }
    
        public int ID { get; set; }
        public int PredavacID { get; set; }
        public string Naslov { get; set; }
        public string Opis { get; set; }
        public Nullable<int> SmjerID { get; set; }
        public Nullable<System.DateTime> VrijemeOdrzavanja { get; set; }
        public Nullable<int> DvoranaID { get; set; }
        public Nullable<int> TipPredavanjaID { get; set; }
        public Nullable<int> Trajanje { get; set; }
    
        public virtual ICollection<PrijaveNaPredavanja> PrijaveNaPredavanjas { get; set; }
    }
}
