//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAnnotationDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vComplexGetdateEtc
    {
        public Nullable<int> a { get; set; }
        public Nullable<float> b { get; set; }
        public Nullable<System.DateTime> c { get; set; }
        public System.DateTime Expr1 { get; set; }
    }
}
