//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAnnotationDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vPregledTvrtki
    {
        public int ID { get; set; }
        public string Naziv { get; set; }
        public string Adresa { get; set; }
        public int GradID { get; set; }
        public int Expr1 { get; set; }
        public string Expr2 { get; set; }
        public string PostanskiBroj { get; set; }
    }
}
