//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAnnotationDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vTvrtkeGroupBy
    {
        public Nullable<int> Broj_firmi { get; set; }
        public string Naziv { get; set; }
        public string Grad { get; set; }
    }
}
