//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RenderingViews.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Knjige
    {
        public Knjige()
        {
            this.Posudbes = new HashSet<Posudbe>();
        }
    
        public int ID { get; set; }
        public string Naslov { get; set; }
        public int PisacID { get; set; }
        public int Kolicina { get; set; }
        public int ZanrID { get; set; }
        public string SlikaURL { get; set; }
        public string Opis { get; set; }
        public Nullable<decimal> Cijena { get; set; }
    
        public virtual Pisci Pisci { get; set; }
        public virtual Zanr Zanr { get; set; }
        public virtual ICollection<Posudbe> Posudbes { get; set; }
    }
}
